// <auto-generated />
using System;
using CMS_Window_Systems_Christopher_Sanderson.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CMS_Window_Systems_Christopher_Sanderson.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210803205404_Database-long")]
    partial class Databaselong
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CMS_Window_Systems_Christopher_Sanderson.Models.Heading", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateInProduction")
                        .HasColumnType("datetime2");

                    b.Property<long>("JobKeyID")
                        .HasMaxLength(8)
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Heading");
                });

            modelBuilder.Entity("CMS_Window_Systems_Christopher_Sanderson.Models.Production", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ItemKeyID")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<long>("JobKeyID")
                        .HasMaxLength(8)
                        .HasColumnType("bigint");

                    b.Property<string>("productName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Production");
                });

            modelBuilder.Entity("CMS_Window_Systems_Christopher_Sanderson.Models.QRTable", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ItemKeyID")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<long>("JobKeyID")
                        .HasMaxLength(8)
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ScanDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("QRTable");
                });
#pragma warning restore 612, 618
        }
    }
}
